DROP TABLE Skill;
DROP TABLE Position;
DROP TABLE Job;
DROP TABLE GICS;
DROP TABLE Sub_Industry;
DROP TABLE Company;
DROP TABLE Course;
DROP TABLE Section;
DROP TABLE Person;

DROP TABLE Works;
DROP TABLE Requires;
DROP TABLE Requires_by_job;
DROP TABLE Teaches;
DROP TABLE Prerequisite;
DROP TABLE Takes;
DROP TABLE Has_Skill;

DROP TABLE Phone;
